name: ebbs pull request event

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install ebbs
      run: |
        pip install ebbs
        pip install eot
    - name: Build
      env:
        repo_username: ${{ secrets.INFRASTRUCTURE_USERNAME }}
        repo_password: ${{ secrets.INFRASTRUCTURE_PASSWORD }}
      run: |
        cd build
        ebbs -v . --config "github.json" --event "pull_request"
