name: ebbs release event

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install ebbs
      run: |
        pip install ebbs
        pip install eot
    - name: Build
      env:
        pypi_username: ${{ secrets.PYPI_USERNAME }}
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        repo_username: ${{ secrets.INFRASTRUCTURE_USERNAME }}
        repo_password: ${{ secrets.INFRASTRUCTURE_PASSWORD }}
      run: |
        cd build
        ebbs -v . --config "github.json" --version "${{ github.event.release.tag_name }}" --event "release"
